### ISSUE TITLE
Coalesce<>(one, two, three) only includes one

### ISSUE THREAD

**Issue by dviry** [csharpsi/Gremlin.Net.Extensions#19]
Thanks for this library, it's great help!

As in the subject, when I use .Coalesce it seems it renders to the querystring only the first traversal? Not sure what I am doing wrong could you maybe try to reproduce it in a unit test case?

Thanks,

Leon

**Comment by csharpsi** [comment]
Hi Leon, thanks for the feedback!

Could you provide a code example please? I'm not quite sure what you're doing here.

**Comment by dviry** [comment]
I actually forked it to provide you a unit test, but I think for now it's easier to paste it here than sending you a PR ;)

```
        [Fact]
        public void TestToGremlinQueryCoalesce()
        {
            string query = _g.V("thomas")
                .Coalesce<string>(
                    Has("id", "robin"),
                    Has("id", "leon"))
                .ToGremlinQuery();

            query.Should().Be("g.V('thomas').coalesce(has('id', 'robin'), has('id', 'leon')");
        }
```

This fails - .ToGremlinQuery() returns:
```
g.V('thomas').coalesce(has('id', 'robin'))"
```

Which is not what I expected...

**Comment by csharpsi** [comment]
Ah ok I see. Feel free to submit a pull request if you want to. Looks like a bug for sure

**Comment by csharpsi** [comment]
Available on nuget.org from version 0.3.0
